# Generated by Django 4.1.4 on 2023-01-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='atm',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
