# Generated by Django 4.1.2 on 2023-01-06 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_atm_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atm',
            old_name='location',
            new_name='location_type',
        ),
    ]
