# Generated by Django 4.1.2 on 2023-01-06 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_location_atm_location_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revenue',
            name='yearly',
        ),
    ]
