# Generated by Django 4.1.2 on 2023-01-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_revenue_options_cashinput'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashinput',
            name='date',
            field=models.DateField(verbose_name='Date Cash Added'),
        ),
    ]
