# Generated by Django 4.1.4 on 2023-01-09 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_revenue_options'),
        ('main_app', '0007_alter_revenue_options_cashinput'),
    ]

    operations = [
    ]
