# Generated by Django 4.1.4 on 2023-01-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_merge_20230109_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashinput',
            name='date',
            field=models.DateField(verbose_name='Date Cash Added'),
        ),
    ]
