# Generated by Django 4.1.2 on 2023-01-09 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_cashinput_date'),
        ('main_app', '0009_alter_cashinput_date'),
    ]

    operations = [
    ]
